"use client";

import { createClient } from "@/lib/supabase/client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import jsPDF from "jspdf";

type Document = {
  id: string;
  type: string;
  number: string;
  client_name: string;
  client_email: string;
  description: string;
  labour_cost: number;
  materials_cost: number;
  vat: boolean;
  total: number;
  status: string;
  created_at: string;
};

function generatePDF(doc: Document) {
  const pdf = new jsPDF();
  const date = new Date(doc.created_at).toLocaleDateString("en-GB");
  const labour = doc.labour_cost;
  const materials = doc.materials_cost;
  const vatAmount = doc.vat ? (labour + materials) * 0.2 : 0;
  const isInvoice = doc.type === "invoice";
  const title = isInvoice ? "INVOICE" : "QUOTE";

  pdf.setFillColor(0, 150, 80);
  pdf.rect(0, 0, 210, 35, "F");
  pdf.setFontSize(20);
  pdf.setTextColor(255, 255, 255);
  pdf.text(title, 14, 16);
  pdf.setFontSize(10);
  pdf.setTextColor(200, 255, 220);
  pdf.text(`REF: ${doc.number}`, 14, 26);
  pdf.text(date, 196, 26, { align: "right" });

  pdf.setFillColor(0, 150, 80);
  pdf.rect(14, 44, 3, 28, "F");
  pdf.setFontSize(9);
  pdf.setTextColor(0, 150, 80);
  pdf.text("PREPARED FOR", 22, 52);
  pdf.setFontSize(13);
  pdf.setTextColor(0);
  pdf.text(doc.client_name || "Client", 22, 61);
  pdf.setFontSize(10);
  pdf.setTextColor(100);
  pdf.text(doc.client_email || "", 22, 69);

  pdf.setDrawColor(0, 150, 80);
  pdf.line(14, 80, 196, 80);

  pdf.setFontSize(9);
  pdf.setTextColor(0, 150, 80);
  pdf.text("SCOPE OF WORK", 14, 90);
  pdf.setFontSize(11);
  pdf.setTextColor(0);
  const descLines = pdf.splitTextToSize(doc.description || "", 170);
  pdf.text(descLines, 14, 98);

  const costsY = 98 + descLines.length * 6 + 12;
  pdf.setFillColor(245, 255, 250);
  pdf.rect(14, costsY - 4, 182, doc.vat ? 42 : 34, "F");
  pdf.setFontSize(10);
  pdf.setTextColor(60);
  pdf.text("Labour", 20, costsY + 4);
  pdf.text(`£${labour.toFixed(2)}`, 190, costsY + 4, { align: "right" });
  pdf.text("Materials", 20, costsY + 12);
  pdf.text(`£${materials.toFixed(2)}`, 190, costsY + 12, { align: "right" });
  if (doc.vat) {
    pdf.text("VAT (20%)", 20, costsY + 20);
    pdf.text(`£${vatAmount.toFixed(2)}`, 190, costsY + 20, { align: "right" });
  }

  const totalY = costsY + (doc.vat ? 32 : 24);
  pdf.setDrawColor(0, 150, 80);
  pdf.line(14, totalY, 196, totalY);
  pdf.setFontSize(13);
  pdf.setTextColor(0, 150, 80);
  pdf.text("Total", 20, totalY + 10);
  pdf.text(`£${doc.total.toFixed(2)}`, 190, totalY + 10, { align: "right" });

  if (isInvoice) {
    pdf.setFontSize(10);
    pdf.setTextColor(100);
    pdf.text("Payment due within 30 days of invoice date.", 105, totalY + 26, { align: "center" });
  }

  pdf.setFontSize(8);
  pdf.setTextColor(180);
  pdf.text("Generated by GetJobQuotes.app", 105, 285, { align: "center" });
  pdf.save(`${doc.type}-${doc.number}.pdf`);
}

export default function DashboardPage() {
  const supabase = createClient();
  const router = useRouter();

  const [userEmail, setUserEmail] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [documents, setDocuments] = useState<Document[]>([]);
  const [converting, setConverting] = useState<string | null>(null);
  const [deleting, setDeleting] = useState<string | null>(null);

  useEffect(() => {
    const init = async () => {
      const { data } = await supabase.auth.getUser();
      if (!data.user) {
        router.push("/auth?mode=login");
        return;
      }
      setUserEmail(data.user.email || null);
      await loadDocuments();
      setLoading(false);
    };
    init();
  }, []);

  const loadDocuments = async () => {
    const { data } = await supabase
      .from("documents")
      .select("*")
      .order("created_at", { ascending: false });
    if (data) setDocuments(data);
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Delete this document?")) return;
    setDeleting(id);
    await supabase.from("documents").delete().eq("id", id);
    await loadDocuments();
    setDeleting(null);
  };

  const handleConvertToInvoice = async (doc: Document) => {
    setConverting(doc.id);
    const { data: userData } = await supabase.auth.getUser();
    const invoiceNumber = `INV-${Date.now()}`;
    await supabase.from("documents").insert({
      user_id: userData.user?.id,
      type: "invoice",
      number: invoiceNumber,
      client_name: doc.client_name,
      client_email: doc.client_email,
      description: doc.description,
      labour_cost: doc.labour_cost,
      materials_cost: doc.materials_cost,
      vat: doc.vat,
      total: doc.total,
      status: "unpaid",
      linked_quote_id: doc.id,
    });
    setConverting(null);
    await loadDocuments();
  };

  const logout = async () => {
    await supabase.auth.signOut();
    router.push("/auth?mode=login");
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center">
        Loading dashboard...
      </div>
    );
  }

  const quotes = documents.filter((d) => d.type === "quote");
  const invoices = documents.filter((d) => d.type === "invoice");

  return (
    <div className="min-h-screen bg-black px-6 py-10 text-white">
      <div className="mx-auto max-w-4xl">

        {/* Header */}
        <div className="mb-8 flex items-center justify-between border-b border-green-600/20 pb-4">
          <h1 className="text-3xl font-bold text-green-500">Dashboard</h1>
          <div className="flex items-center gap-4">
            <span className="text-sm text-zinc-400">{userEmail}</span>
            <button onClick={logout}
              className="rounded-lg border border-zinc-600 px-4 py-2 text-sm text-zinc-400 transition hover:border-green-500 hover:text-green-400">
              Log Out
            </button>
          </div>
        </div>

        {/* New Quote Button */}
        <button onClick={() => router.push("/tool")}
          className="mb-10 w-full rounded-xl bg-green-600 py-4 text-lg font-bold text-white transition hover:bg-green-500">
          + New Quote
        </button>

        {/* Quotes */}
        <div className="mb-10">
          <h2 className="mb-4 text-xl font-semibold text-white">
            Quotes <span className="text-sm text-zinc-500 font-normal">({quotes.length})</span>
          </h2>
          {quotes.length === 0 ? (
            <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-8 text-center text-zinc-500">
              No quotes yet. Hit <span className="text-green-400">+ New Quote</span> to create your first one.
            </div>
          ) : (
            <div className="space-y-3">
              {quotes.map((doc) => (
                <div key={doc.id} className="rounded-xl border border-zinc-800 bg-zinc-900 p-4">
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <p className="font-semibold text-white text-lg">{doc.client_name || "No client name"}</p>
                      <p className="text-sm text-zinc-400">{doc.number} · {new Date(doc.created_at).toLocaleDateString("en-GB")}</p>
                      <p className="mt-1 text-sm text-zinc-500">{doc.description?.slice(0, 80)}{doc.description?.length > 80 ? "..." : ""}</p>
                    </div>
                    <div className="text-right shrink-0 ml-4">
                      <p className="text-xl font-bold text-green-400">£{doc.total.toFixed(2)}</p>
                      <span className="text-xs text-zinc-500 bg-zinc-800 px-2 py-0.5 rounded-full">{doc.status}</span>
                    </div>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <button onClick={() => generatePDF(doc)}
                      className="rounded-lg bg-green-600 px-3 py-2 text-xs font-semibold text-white transition hover:bg-green-500">
                      Download PDF
                    </button>
                    <button onClick={() => handleConvertToInvoice(doc)}
                      disabled={converting === doc.id}
                      className="rounded-lg bg-zinc-700 px-3 py-2 text-xs font-semibold text-white transition hover:bg-zinc-600 disabled:opacity-50">
                      {converting === doc.id ? "Converting..." : "Convert to Invoice"}
                    </button>
                    <button onClick={() => handleDelete(doc.id)}
                      disabled={deleting === doc.id}
                      className="rounded-lg bg-red-900/30 px-3 py-2 text-xs font-semibold text-red-400 transition hover:bg-red-900/60 disabled:opacity-50">
                      {deleting === doc.id ? "Deleting..." : "Delete"}
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Invoices */}
        <div>
          <h2 className="mb-4 text-xl font-semibold text-white">
            Invoices <span className="text-sm text-zinc-500 font-normal">({invoices.length})</span>
          </h2>
          {invoices.length === 0 ? (
            <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-8 text-center text-zinc-500">
              No invoices yet. Convert a quote to generate one.
            </div>
          ) : (
            <div className="space-y-3">
              {invoices.map((doc) => (
                <div key={doc.id} className="rounded-xl border border-zinc-800 bg-zinc-900 p-4">
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <p className="font-semibold text-white text-lg">{doc.client_name || "No client name"}</p>
                      <p className="text-sm text-zinc-400">{doc.number} · {new Date(doc.created_at).toLocaleDateString("en-GB")}</p>
                      <p className="mt-1 text-sm text-zinc-500">{doc.description?.slice(0, 80)}{doc.description?.length > 80 ? "..." : ""}</p>
                    </div>
                    <div className="text-right shrink-0 ml-4">
                      <p className="text-xl font-bold text-green-400">£{doc.total.toFixed(2)}</p>
                      <span className="text-xs text-zinc-500 bg-zinc-800 px-2 py-0.5 rounded-full">{doc.status}</span>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <button onClick={() => generatePDF(doc)}
                      className="rounded-lg bg-green-600 px-3 py-2 text-xs font-semibold text-white transition hover:bg-green-500">
                      Download PDF
                    </button>
                    <button onClick={() => handleDelete(doc.id)}
                      disabled={deleting === doc.id}
                      className="rounded-lg bg-red-900/30 px-3 py-2 text-xs font-semibold text-red-400 transition hover:bg-red-900/60 disabled:opacity-50">
                      {deleting === doc.id ? "Deleting..." : "Delete"}
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

      </div>
    </div>
  );
}
