"use client";

import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import jsPDF from "jspdf";

type Template = "minimal" | "modern" | "formal" | "branded";

const TEMPLATES: { id: Template; name: string; desc: string }[] = [
  { id: "minimal", name: "Clean / Minimal", desc: "Simple, lots of whitespace" },
  { id: "modern", name: "Bold / Modern", desc: "Strong header, clean lines" },
  { id: "formal", name: "Classic / Formal", desc: "Traditional business style" },
  { id: "branded", name: "Branded", desc: "Green accent, your brand colours" },
];

function generateMinimal(doc: jsPDF, form: any, quoteNumber: string, date: string, labour: number, materials: number, vatAmount: number, total: number) {
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text(quoteNumber, 196, 20, { align: "right" });
  doc.text(date, 196, 27, { align: "right" });

  doc.setFontSize(24);
  doc.setTextColor(0);
  doc.text(form.business_name || "Your Business", 14, 30);

  doc.setDrawColor(220);
  doc.line(14, 35, 196, 35);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("PREPARED FOR", 14, 46);
  doc.setTextColor(0);
  doc.setFontSize(12);
  doc.text(form.client_name || "Client Name", 14, 54);
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(form.client_email || "", 14, 61);

  doc.setDrawColor(220);
  doc.line(14, 68, 196, 68);

  doc.setTextColor(100);
  doc.setFontSize(10);
  doc.text("SCOPE OF WORK", 14, 78);
  doc.setTextColor(0);
  doc.setFontSize(11);
  const descLines = doc.splitTextToSize(form.description || "", 170);
  doc.text(descLines, 14, 86);

  const costsY = 86 + descLines.length * 6 + 12;
  doc.setTextColor(100);
  doc.text("Labour", 14, costsY);
  doc.text(`£${labour.toFixed(2)}`, 196, costsY, { align: "right" });
  doc.text("Materials", 14, costsY + 8);
  doc.text(`£${materials.toFixed(2)}`, 196, costsY + 8, { align: "right" });
  if (form.vat) {
    doc.text("VAT (20%)", 14, costsY + 16);
    doc.text(`£${vatAmount.toFixed(2)}`, 196, costsY + 16, { align: "right" });
  }

  const totalY = costsY + (form.vat ? 28 : 20);
  doc.setDrawColor(0);
  doc.line(14, totalY, 196, totalY);
  doc.setFontSize(13);
  doc.setTextColor(0);
  doc.text("Total", 14, totalY + 10);
  doc.text(`£${total.toFixed(2)}`, 196, totalY + 10, { align: "right" });

  doc.setFontSize(8);
  doc.setTextColor(180);
  doc.text("Generated by GetJobQuotes.app", 105, 285, { align: "center" });
}

function generateModern(doc: jsPDF, form: any, quoteNumber: string, date: string, labour: number, materials: number, vatAmount: number, total: number) {
  // Bold dark header bar
  doc.setFillColor(20, 20, 20);
  doc.rect(0, 0, 210, 40, "F");

  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text(form.business_name || "Your Business", 14, 18);
  doc.setFontSize(10);
  doc.setTextColor(180, 180, 180);
  doc.text("QUOTE", 14, 28);
  doc.text(quoteNumber, 196, 22, { align: "right" });
  doc.setTextColor(140, 140, 140);
  doc.text(date, 196, 30, { align: "right" });

  // Client block
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text("CLIENT", 14, 54);
  doc.setFontSize(13);
  doc.setTextColor(0);
  doc.text(form.client_name || "Client Name", 14, 62);
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(form.client_email || "", 14, 70);

  // Description box
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(14, 80, 182, 10 + (doc.splitTextToSize(form.description || "", 170).length * 6), 2, 2, "F");
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text("JOB DESCRIPTION", 20, 89);
  doc.setFontSize(11);
  doc.setTextColor(0);
  const descLines = doc.splitTextToSize(form.description || "", 162);
  doc.text(descLines, 20, 97);

  const costsY = 97 + descLines.length * 6 + 14;

  // Cost rows
  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text("Labour", 14, costsY);
  doc.text(`£${labour.toFixed(2)}`, 196, costsY, { align: "right" });
  doc.text("Materials", 14, costsY + 9);
  doc.text(`£${materials.toFixed(2)}`, 196, costsY + 9, { align: "right" });
  if (form.vat) {
    doc.text("VAT (20%)", 14, costsY + 18);
    doc.text(`£${vatAmount.toFixed(2)}`, 196, costsY + 18, { align: "right" });
  }

  const totalY = costsY + (form.vat ? 28 : 20);
  doc.setFillColor(20, 20, 20);
  doc.rect(14, totalY, 182, 14, "F");
  doc.setFontSize(12);
  doc.setTextColor(255);
  doc.text("TOTAL", 20, totalY + 9);
  doc.text(`£${total.toFixed(2)}`, 190, totalY + 9, { align: "right" });

  doc.setFontSize(8);
  doc.setTextColor(180);
  doc.text("Generated by GetJobQuotes.app", 105, 285, { align: "center" });
}

function generateFormal(doc: jsPDF, form: any, quoteNumber: string, date: string, labour: number, materials: number, vatAmount: number, total: number) {
  // Classic centered header
  doc.setFontSize(20);
  doc.setTextColor(0);
  doc.text(form.business_name || "Your Business", 105, 22, { align: "center" });

  doc.setDrawColor(0);
  doc.line(14, 28, 196, 28);
  doc.line(14, 30, 196, 30);

  doc.setFontSize(14);
  doc.text("QUOTATION", 105, 42, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(80);
  doc.text(`Quote Ref: ${quoteNumber}`, 14, 55);
  doc.text(`Date: ${date}`, 196, 55, { align: "right" });

  doc.setDrawColor(180);
  doc.line(14, 60, 196, 60);

  doc.setTextColor(0);
  doc.setFontSize(10);
  doc.text("To:", 14, 72);
  doc.setFontSize(11);
  doc.text(form.client_name || "Client Name", 30, 72);
  doc.setFontSize(10);
  doc.setTextColor(80);
  doc.text(form.client_email || "", 30, 80);

  doc.setTextColor(0);
  doc.setFontSize(10);
  doc.text("Re:", 14, 94);
  const descLines = doc.splitTextToSize(form.description || "", 160);
  doc.text(descLines, 30, 94);

  const costsY = 94 + descLines.length * 6 + 14;

  // Formal table
  doc.setFillColor(240, 240, 240);
  doc.rect(14, costsY - 6, 182, 8, "F");
  doc.setFontSize(10);
  doc.setTextColor(0);
  doc.text("Description", 18, costsY);
  doc.text("Amount", 188, costsY, { align: "right" });

  doc.setDrawColor(200);
  doc.line(14, costsY + 3, 196, costsY + 3);

  doc.text("Labour", 18, costsY + 12);
  doc.text(`£${labour.toFixed(2)}`, 188, costsY + 12, { align: "right" });
  doc.text("Materials", 18, costsY + 20);
  doc.text(`£${materials.toFixed(2)}`, 188, costsY + 20, { align: "right" });
  if (form.vat) {
    doc.text("VAT @ 20%", 18, costsY + 28);
    doc.text(`£${vatAmount.toFixed(2)}`, 188, costsY + 28, { align: "right" });
  }

  const totalY = costsY + (form.vat ? 38 : 30);
  doc.setFillColor(220, 220, 220);
  doc.rect(14, totalY - 6, 182, 10, "F");
  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text("Total Amount Due", 18, totalY + 1);
  doc.text(`£${total.toFixed(2)}`, 188, totalY + 1, { align: "right" });

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text("This quotation is valid for 30 days from the date above.", 105, totalY + 18, { align: "center" });

  doc.setFontSize(8);
  doc.setTextColor(180);
  doc.text("Generated by GetJobQuotes.app", 105, 285, { align: "center" });
}

function generateBranded(doc: jsPDF, form: any, quoteNumber: string, date: string, labour: number, materials: number, vatAmount: number, total: number) {
  // Green accent header
  doc.setFillColor(0, 150, 80);
  doc.rect(0, 0, 210, 35, "F");

  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text(form.business_name || "Your Business", 14, 16);
  doc.setFontSize(10);
  doc.setTextColor(200, 255, 220);
  doc.text("Professional Quote", 14, 26);
  doc.text(date, 196, 26, { align: "right" });

  // Green accent left bar
  doc.setFillColor(0, 150, 80);
  doc.rect(14, 44, 3, 30, "F");

  doc.setFontSize(9);
  doc.setTextColor(0, 150, 80);
  doc.text("PREPARED FOR", 22, 52);
  doc.setFontSize(13);
  doc.setTextColor(0);
  doc.text(form.client_name || "Client Name", 22, 61);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(form.client_email || "", 22, 69);

  doc.setFontSize(9);
  doc.setTextColor(0, 150, 80);
  doc.text(`REF: ${quoteNumber}`, 196, 52, { align: "right" });

  doc.setDrawColor(0, 150, 80);
  doc.line(14, 82, 196, 82);

  doc.setFontSize(9);
  doc.setTextColor(0, 150, 80);
  doc.text("SCOPE OF WORK", 14, 92);
  doc.setFontSize(11);
  doc.setTextColor(0);
  const descLines = doc.splitTextToSize(form.description || "", 170);
  doc.text(descLines, 14, 100);

  const costsY = 100 + descLines.length * 6 + 12;

  doc.setFillColor(245, 255, 250);
  doc.rect(14, costsY - 4, 182, form.vat ? 42 : 34, "F");

  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text("Labour", 20, costsY + 4);
  doc.text(`£${labour.toFixed(2)}`, 190, costsY + 4, { align: "right" });
  doc.text("Materials", 20, costsY + 12);
  doc.text(`£${materials.toFixed(2)}`, 190, costsY + 12, { align: "right" });
  if (form.vat) {
    doc.text("VAT (20%)", 20, costsY + 20);
    doc.text(`£${vatAmount.toFixed(2)}`, 190, costsY + 20, { align: "right" });
  }

  const totalY = costsY + (form.vat ? 32 : 24);
  doc.setDrawColor(0, 150, 80);
  doc.line(14, totalY, 196, totalY);
  doc.setFontSize(13);
  doc.setTextColor(0, 150, 80);
  doc.text("Total", 20, totalY + 10);
  doc.text(`£${total.toFixed(2)}`, 190, totalY + 10, { align: "right" });

  doc.setFontSize(8);
  doc.setTextColor(180);
  doc.text("Generated by GetJobQuotes.app", 105, 285, { align: "center" });
}

export default function ToolPage() {
  const supabase = createClient();
  const router = useRouter();

  const [userEmail, setUserEmail] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [selectedTemplate, setSelectedTemplate] = useState<Template>("minimal");

  const [form, setForm] = useState({
    business_name: "",
    client_name: "",
    client_email: "",
    description: "",
    labour_cost: "",
    materials_cost: "",
    vat: false,
  });

  useEffect(() => {
    const checkUser = async () => {
      const { data } = await supabase.auth.getUser();
      if (!data.user) {
        router.push("/auth?mode=login");
        return;
      }
      setUserEmail(data.user.email || null);
      setLoading(false);
    };
    checkUser();
  }, [router, supabase]);

  const labour = parseFloat(form.labour_cost) || 0;
  const materials = parseFloat(form.materials_cost) || 0;
  const subtotal = labour + materials;
  const vatAmount = form.vat ? subtotal * 0.2 : 0;
  const total = subtotal + vatAmount;

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const target = e.target as HTMLInputElement;
    const value = target.type === "checkbox" ? target.checked : target.value;
    setForm((prev) => ({ ...prev, [target.name]: value }));
  };

  const handleSave = async () => {
    setSaving(true);
    setMessage("");
    const { data: userData } = await supabase.auth.getUser();
    if (!userData.user) return;
    const quoteNumber = `Q-${Date.now()}`;
    const { error } = await supabase.from("documents").insert({
      user_id: userData.user.id,
      type: "quote",
      number: quoteNumber,
      client_name: form.client_name,
      client_email: form.client_email,
      description: form.description,
      labour_cost: labour,
      materials_cost: materials,
      vat: form.vat,
      total: total,
      status: "draft",
    });
    setSaving(false);
    if (error) {
      setMessage("Error saving quote: " + error.message);
    } else {
      setMessage("Quote saved successfully.");
      setTimeout(() => router.push("/dashboard"), 1500);
    }
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const quoteNumber = `Q-${Date.now()}`;
    const date = new Date().toLocaleDateString("en-GB");

    if (selectedTemplate === "minimal") generateMinimal(doc, form, quoteNumber, date, labour, materials, vatAmount, total);
    if (selectedTemplate === "modern") generateModern(doc, form, quoteNumber, date, labour, materials, vatAmount, total);
    if (selectedTemplate === "formal") generateFormal(doc, form, quoteNumber, date, labour, materials, vatAmount, total);
    if (selectedTemplate === "branded") generateBranded(doc, form, quoteNumber, date, labour, materials, vatAmount, total);

    doc.save(`quote-${quoteNumber}.pdf`);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center">
        Loading...
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-black px-6 py-10 text-white">
      <div className="mx-auto max-w-2xl">

        <div className="mb-8 flex items-center justify-between border-b border-green-600/20 pb-4">
          <h1 className="text-3xl font-bold text-green-500">New Quote</h1>
          <span className="text-sm text-zinc-400">{userEmail}</span>
        </div>

        <div className="space-y-4 rounded-2xl border border-zinc-800 bg-zinc-900 p-6">

          <div>
            <label className="mb-1 block text-sm text-zinc-400">Your Business Name</label>
            <input name="business_name" value={form.business_name} onChange={handleChange}
              placeholder="e.g. Smith Plumbing Ltd"
              className="w-full rounded-lg border border-zinc-700 bg-black px-4 py-3 text-white outline-none focus:border-green-500" />
          </div>

          <div>
            <label className="mb-1 block text-sm text-zinc-400">Client Name</label>
            <input name="client_name" value={form.client_name} onChange={handleChange}
              placeholder="e.g. John Davies"
              className="w-full rounded-lg border border-zinc-700 bg-black px-4 py-3 text-white outline-none focus:border-green-500" />
          </div>

          <div>
            <label className="mb-1 block text-sm text-zinc-400">Client Email</label>
            <input name="client_email" value={form.client_email} onChange={handleChange}
              placeholder="e.g. john@example.com"
              className="w-full rounded-lg border border-zinc-700 bg-black px-4 py-3 text-white outline-none focus:border-green-500" />
          </div>

          <div>
            <label className="mb-1 block text-sm text-zinc-400">Job Description</label>
            <textarea name="description" value={form.description} onChange={handleChange}
              placeholder="Describe the work to be done..."
              rows={4}
              className="w-full rounded-lg border border-zinc-700 bg-black px-4 py-3 text-white outline-none focus:border-green-500" />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="mb-1 block text-sm text-zinc-400">Labour Cost (£)</label>
              <input name="labour_cost" value={form.labour_cost} onChange={handleChange}
                type="number" placeholder="0.00"
                className="w-full rounded-lg border border-zinc-700 bg-black px-4 py-3 text-white outline-none focus:border-green-500" />
            </div>
            <div>
              <label className="mb-1 block text-sm text-zinc-400">Materials Cost (£)</label>
              <input name="materials_cost" value={form.materials_cost} onChange={handleChange}
                type="number" placeholder="0.00"
                className="w-full rounded-lg border border-zinc-700 bg-black px-4 py-3 text-white outline-none focus:border-green-500" />
            </div>
          </div>

          <div className="flex items-center gap-3">
            <input type="checkbox" name="vat" id="vat" checked={form.vat} onChange={handleChange}
              className="h-4 w-4 accent-green-500" />
            <label htmlFor="vat" className="text-sm text-zinc-400">Add VAT (20%)</label>
          </div>

          <div className="rounded-lg border border-zinc-700 bg-black p-4 space-y-1">
            <div className="flex justify-between text-sm text-zinc-400">
              <span>Subtotal</span><span>£{subtotal.toFixed(2)}</span>
            </div>
            {form.vat && (
              <div className="flex justify-between text-sm text-zinc-400">
                <span>VAT (20%)</span><span>£{vatAmount.toFixed(2)}</span>
              </div>
            )}
            <div className="flex justify-between text-lg font-bold text-white border-t border-zinc-700 pt-2 mt-2">
              <span>Total</span><span>£{total.toFixed(2)}</span>
            </div>
          </div>

          {/* Template Selector */}
          <div>
            <label className="mb-2 block text-sm text-zinc-400">Choose Template</label>
            <div className="grid grid-cols-2 gap-3">
              {TEMPLATES.map((t) => (
                <button
                  key={t.id}
                  onClick={() => setSelectedTemplate(t.id)}
                  className={`rounded-lg border px-4 py-3 text-left transition ${
                    selectedTemplate === t.id
                      ? "border-green-500 bg-green-600/10 text-white"
                      : "border-zinc-700 bg-black text-zinc-400 hover:border-zinc-500"
                  }`}
                >
                  <div className="font-semibold text-sm">{t.name}</div>
                  <div className="text-xs mt-1 opacity-70">{t.desc}</div>
                </button>
              ))}
            </div>
          </div>

          {message && (
            <p className="text-center text-sm text-green-400">{message}</p>
          )}

          <div className="grid grid-cols-2 gap-4">
            <button onClick={handleSave} disabled={saving}
              className="w-full rounded-lg bg-zinc-700 py-3 font-semibold text-white transition hover:bg-zinc-600 disabled:opacity-60">
              {saving ? "Saving..." : "Save Quote"}
            </button>
            <button onClick={handleDownloadPDF}
              className="w-full rounded-lg bg-green-600 py-3 font-semibold text-white transition hover:bg-green-500">
              Download PDF
            </button>
          </div>

        </div>
      </div>
    </div>
  );
}
